"""Score self-eval predictions with the organizer eval_metrics.py.

The official eval inputs do not include ground truth, so this script scores only
the local self_eval split generated by make_selfeval.py. It is intended for
report reproduction and sanity checks before submitting the official CSVs.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SCORER = ROOT / "tracks" / "industrial-infineon" / "participant_files" / "eval_metrics.py"
SELF_EVAL = ROOT / "self_eval"


def run(task: str, predictions: Path, ground_truth: Path, supplement: Path | None = None) -> None:
    cmd = [
        sys.executable,
        str(SCORER),
        "--task",
        task,
        "--ground-truth",
        str(ground_truth),
        "--predictions",
        str(predictions),
    ]
    if supplement is not None:
        cmd.extend(["--valid-supplement", str(supplement)])
    print(f"\n$ {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pred-dir",
        default="self_eval/gpt_large_submission",
        help="Directory containing nextstep.csv, completion.csv, and anomaly.csv.",
    )
    args = parser.parse_args()
    pred_dir = ROOT / args.pred_dir

    run("next-step", pred_dir / "nextstep.csv", SELF_EVAL / "ground_truth_valid.csv")
    run("completion", pred_dir / "completion.csv", SELF_EVAL / "ground_truth_valid.csv")
    run(
        "anomaly",
        pred_dir / "anomaly.csv",
        SELF_EVAL / "ground_truth_anomaly_forbidden.csv",
        SELF_EVAL / "ground_truth_anomaly_valid_supplement.csv",
    )


if __name__ == "__main__":
    main()
