_wandb:
    value:
        cli_version: 0.27.0
        e:
            qi5cltp2yc044csqj067qoq8zccnu3uy:
                args:
                    - --model
                    - gpt2
                    - --max_eval_examples
                    - "100"
                    - --train_dir
                    - ../tracks/industrial-infineon/training_data
                    - --wandb_project
                    - industrial-ai-hackathon
                    - --seed
                    - "42"
                codePath: test_baseline_1\baseline_llm_zeroshot.py
                codePathLocal: baseline_llm_zeroshot.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "768014807040"
                        used: "527891808256"
                email: angiezaya7@gmail.com
                executable: D:\Angie\3. IMC Krems\Masters\Hackathon_2026\venv\Scripts\python.exe
                git:
                    commit: e5df1f4df86e578537eac4fa510ffd6fcd1d66b8
                    remote: https://github.com/AriunZaya7/zero_one_hack_0625.git
                host: LAPTOP-UBNDF6IL
                memory:
                    total: "16505954304"
                os: Windows-10-10.0.26200-SP0
                program: D:\Angie\3. IMC Krems\Masters\Hackathon_2026\zero_one_hack_0625\test_baseline_1\baseline_llm_zeroshot.py
                python: CPython 3.11.3
                root: D:\Angie\3. IMC Krems\Masters\Hackathon_2026\zero_one_hack_0625\test_baseline_1
                startedAt: "2026-05-29T22:07:37.107843Z"
                writerId: qi5cltp2yc044csqj067qoq8zccnu3uy
        m: []
        python_version: 3.11.3
        t:
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.3
            "5": 0.27.0
            "8":
                - 3
            "12": 0.27.0
            "13": windows-amd64
baseline:
    value: llm_zeroshot
max_eval_examples:
    value: 100
model:
    value: gpt2
seed:
    value: 42
val_frac:
    value: 0.1
